# Generated by Django 4.1.7 on 2023-04-01 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.TextField(max_length=255)),
                ('value', models.FloatField()),
                ('pay', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
